# -*- coding: utf-8 -*-
"""Atividade1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12xHvMEyP0o9XFOY5YMs5UeVQBZaQSAdX
"""

sabores_pizza = ["Portuguesa", "Baiana", "Á Moda", "Frango Supremo", "Palmito"]
anos_nascimento = [1976, 1984, 1986, 2017, 2018]
print("Sabores de pizzas favoritas: " + str(sabores_pizza))
print("Anos de nascimentos familiares: " + str(anos_nascimento))